[package]
name = "rgalaxy"
version = "0.1.0"
authors = ["Stas <jinfar@ymail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.8"
rand = "0.8.3"
rand_distr = "0.4.0"
